python crfm_test.py \
    --pretrained_model_name_or_path sd3.5_medium \
    --data_root demo \
    --json_file demo/index_.jsonl \
    --lora_ckpt xx \
    --vectors_path vectors/demo \
    --batch_size 1 \
    --debug 1 \
    --num_cls 18 \
    --mmseg_config xx \
    --mmseg_ckpt xx \
    --num_inference_steps 23 \
    --rectified_step 4